name:  BrowserUpdateWarning
author:  andyfleming
current:  1.0.8
category:  Utilities
tags:  [browser,updates,check]
docs:  https://github.com/andyfleming/BrowserUpdateWarning
demo:  https://github.com/andyfleming/BrowserUpdateWarning